## 肠道菌群与免疫

### 核心文章列表

```{r immune-article-datatable, fig.cap=""}
i <- 2
topic_header <- topic[["immunity"]]
topic_caption <- paste0(topic_header,"研究核心论文")

# 文章列表
df <- topic_articles_core[["immunity"]]
df <- biblio_df(df)
produce_topic_article_datatable(df, caption = topic_caption, filename = topic_caption)
```


```{r immune-article-trend, fig.cap="肠道菌群与免疫相关文献增长趋势"}
topic_trend_core_plot_list[["immunity"]]
```


### 核心(研究）论文引用历史脉络


```{r immune-article-histnet, fig.cap="肠道菌群与免疫核心论文引用历史脉络"}
safe_histNetwork <- purrr::possibly(histNetwork, NULL)
hist_result <- safe_histNetwork(filter(df,DT=="ARTICLE"),verbose = FALSE)
safe_histPlot <- purrr::possibly(histPlot,NULL)
hisgraph <- safe_histPlot(hist_result,verbose = F,n=30,size = 8,labelsize = 3)
```

### 领域内专家  


```{r immune-article-top-author, fig.cap="肠道菌群与免疫领域内顶尖专家"}
topAU <- authorProdOverTime(df, k=10, graph = TRUE)
```


### 作者合作网络

```{r immune-article-author-collaboration-network, fig.cap="免疫相关文献的作者合作网络"}
## Author collaboration
NetMatrix <- biblioNetwork(df, analysis = "collaboration", network = "authors", sep = ";")
net = networkPlot(NetMatrix,  normalize = "salton", weighted=NULL, n = 30, Title = "Author collaboration", type = "fruchterman", size=5,size.cex=T,remove.multiple=TRUE,labelsize=0.8,label.n=10,label.cex=F,cluster="louvain",halo = TRUE)
```


### 机构合作网络


```{r immune-article-university-collaboration-network, fig.cap="免疫相关研究机构的合作网络"}
## 机构合作网络（显示前 15 家）
NetMatrix <- biblioNetwork(df, analysis = "collaboration", network = "universities", sep = ";")
net = networkPlot(NetMatrix, n = 15, Title = "Universities Collaboration", 
                type = "fruchterman", size=TRUE, remove.multiple=FALSE,labelsize=0.7,cluster="louvain",
                curved = TRUE,halo = TRUE)
```

### 共词分析

```{r immune-article-conceptual-structure, fig.cap="免疫相关关键词的关联分析"}
# 共词分析
safe_conceptualStructure <- possibly(conceptualStructure,NULL)
CS <- safe_conceptualStructure(df, field = "AB", method = "MDS",clust=5, minDegree = round(nrow(df)/5), stemming = FALSE, labelsize = 10, documents = 30,graph = FALSE)
CS$graph_terms
```

### 研究主题地图

```{r immune-article-thematicmap, fig.cap="免疫相关研究主题地图"}
## Thematic Map
safe_thematicMap <- purrr::possibly(thematicMap, NULL)
Map <- safe_thematicMap(df, field="ID",n=250,minfreq = 5,stemming = FALSE,size = 0.5, n.labels = 3, repel = TRUE)
Map$map
```
